# Generated by Django 3.0.7 on 2020-06-25 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_information',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('bmi', models.FloatField()),
                ('children', models.IntegerField()),
                ('smoker', models.CharField(max_length=3)),
                ('region', models.CharField(max_length=100)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=20)),
                ('telephone_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'personal_information',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
                ('dose', models.FloatField()),
                ('date_time', models.DateTimeField()),
                ('amka', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_app.Personal_information')),
            ],
            options={
                'verbose_name_plural': 'appointment',
            },
        ),
    ]
