# Generated by Django 3.0.7 on 2020-07-03 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200703_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='amka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_app.Personal_information'),
        ),
    ]
